### ISSUE TITLE
can't change the language

### ISSUE THREAD

**Issue by chronoss09** [nikolaevich23/PyPS3checkerGui#2]
![Capture d’écran 2023-03-10 114418](https://user-images.githubusercontent.com/17669980/224296196-fde7c525-2c42-4761-832b-bf6cabfdc06d.png)

**Comment by nikolaevich23** [comment]
replace [this file](https://github.com/nikolaevich23/PyPS3checkerGui/blob/master/config.ini) or choose from this menu:

![Захват-1](https://user-images.githubusercontent.com/12558400/224315766-5ae2a386-6c2a-493e-8f8e-294ee9b14a2f.jpg)
